server:
  port: 8081

person:
    lastName: zhangsan${random.uuid}
    age: ${random.int}
    boss: false
    birth: 2017/12/12
    maps: {k1: v1,k2: 12}
    list:
      - ${person.hello}lisi
      - ${person.hello:hello}zhaoliu
    dog:
      name: ${person.lastName}_dog
      age: 2